### ISSUE TITLE
[Feature Request] JAR renaming

### ISSUE THREAD

**Issue by Krutoy242** [LoliKingdom/Bansoukou#2]
Rare mods require **strict .jar file name**, like [ThaumTweaks](https://www.curseforge.com/minecraft/mc-mods/thaumtweaks):

![](https://i.imgur.com/t2jRRJS.png)

This makes unable to use Bansoukou with ThaumTweaks together.

I was planned to use Bansoukou to manually fix issue with [Web and researches](https://github.com/LoliKingdom/Thaumic-Speedup/issues/3).

### Request
Please add feature to **rename .jar file** to custom name or skip renaming at all.

Bansoukou already renaming file to `{FILENAME}-patched.jar`. If i can skip renaming, and file would be modified in place, it would fix my issue with ThaumTweaks.

Also, it would be nice if I can chose file name, for example putting file `__filename.txt` in `bansoukou/` folder, that would not be added to `.jar` but it contents would be used for renaming.

For example, if i want to place DankNull mod on buttom of `mods/` folder i could make file `./DankNull-1.12.2-1.7.101/__filename.txt` with content:
```
zz_DankNull-1.12.2-1.7.101.jar
```

**Comment by Rongmario** [comment]
I replied over at the [issue thread you opened at ThaumTweaks' repository](https://github.com/GrigLog/ThaumTweaks/issues/24).

I will not be fixing this because it is physically impossible, the reason why I ~~rename~~ duplicate the jar and append a `-patched` after the filename is to circumvent CurseForge's client from deleting the patched jar when the game launches.

I will however think about making the patched jar's name configurable.

**Comment by Rongmario** [comment]
Fixed in v5.
